<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm_repeatedPassword</name>
   <tag></tag>
   <elementGuidId>f0f98a78-900e-4b34-b6a0-e07ea507a619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repeatedPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repeatedPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#repeatedPassword</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecfc3f83-8aa0-4dd2-b6aa-7d75a9664fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>eb7c4b20-1a43-4810-820e-df5f8c56a9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>92c88c7e-5df9-4af7-949f-dd47229ce4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aa58c60-5ed9-4e24-8218-7219dc424241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>adce0f94-74ce-491a-89d7-907bb60ae55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeatedPassword&quot;)</value>
      <webElementGuid>b4dd3bd8-0ba5-453d-a194-f6ba326dca86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repeatedPassword']</value>
      <webElementGuid>eaee1c81-da40-437d-9b68-c6b986307762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerForm']/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>fec01837-8857-472a-b8de-3cd22aa0c4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/input</value>
      <webElementGuid>6f5667a2-79cc-4fdb-ac26-ff32446fd954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'repeatedPassword' and @name = 'repeatedPassword' and @type = 'password']</value>
      <webElementGuid>50a2610c-ebde-4161-bc88-13cba939497a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
