<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>State_required</name>
   <tag></tag>
   <elementGuidId>f46e1586-72b5-49a3-a103-a24537261368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='state-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#state-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;State is required.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>498ad41c-5c62-4974-8c49-d63c072ad043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>state-error</value>
      <webElementGuid>54dfc317-9fad-49c7-839e-b29135b4fb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>e42343c4-9c6d-438c-b083-4f2fae372d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State is required.</value>
      <webElementGuid>552a4cc7-5af7-4201-a935-e407b810c099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state-error&quot;)</value>
      <webElementGuid>7cdccd0c-f9fc-43fd-8f6c-f60d9f79cd84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='state-error']</value>
      <webElementGuid>fc357f0f-ac4a-449f-9d90-b34bbcbe8271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateProfileForm']/form/table/tbody/tr[5]/td[3]/span</value>
      <webElementGuid>2fe4ba97-4f40-45f4-8c62-d8f4a1a11004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State:'])[1]/following::span[1]</value>
      <webElementGuid>c6d7f3ac-f0e0-4dd5-baff-33ea5f6e01bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City is required.'])[1]/following::span[1]</value>
      <webElementGuid>0e409d9f-a5cd-4493-95ea-cdae933d7396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code:'])[1]/preceding::span[1]</value>
      <webElementGuid>14392c72-399d-4623-8a10-4edcf6764d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code is required.'])[1]/preceding::span[1]</value>
      <webElementGuid>e14a6739-8335-424d-be15-86247ae1def5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='State is required.']/parent::*</value>
      <webElementGuid>9ea284ad-b221-482c-84be-1047dcc70297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/span</value>
      <webElementGuid>3b0e333a-022e-4869-bab5-c5c6ebe83012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'state-error' and (text() = 'State is required.' or . = 'State is required.')]</value>
      <webElementGuid>d2109c40-dfd4-48c7-a34b-2ae90200235b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
