<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Trans_Complete_Msg</name>
   <tag></tag>
   <elementGuidId>ec3f14cc-0b3a-4073-bc58-a37e5dd38142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showResult > h1.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='showResult']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Transfer Complete!&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3131a20d-182e-427b-b2c4-e42d9a6bb687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>58b881c7-6337-4a90-a81c-5f8d450cc869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfer Complete!</value>
      <webElementGuid>a9ff2479-e972-413a-9e77-179f03195447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showResult&quot;)/h1[@class=&quot;title&quot;]</value>
      <webElementGuid>75fbd8cc-01e4-48b4-be8a-80df1786108f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showResult']/h1</value>
      <webElementGuid>b1637396-aaf3-4a6c-b051-d853d968c2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount:'])[1]/following::h1[1]</value>
      <webElementGuid>ee6d2330-a0c5-48a5-bc98-67a32f46420b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1.00'])[1]/preceding::h1[1]</value>
      <webElementGuid>e7689742-8c68-4f7e-994d-0b3a724f62cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error!'])[1]/preceding::h1[1]</value>
      <webElementGuid>909425d9-1169-4613-86e1-9cdad0236e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transfer Complete!']/parent::*</value>
      <webElementGuid>414a922c-cb5c-4b56-b2b4-36c29782e88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h1</value>
      <webElementGuid>2af48806-670e-46ef-8517-f53bc4e6c066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Transfer Complete!' or . = 'Transfer Complete!')]</value>
      <webElementGuid>a753825e-3608-48ff-810b-5ac7f150ccb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
