<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FromAcc_DropDown</name>
   <tag></tag>
   <elementGuidId>7119741b-9897-4987-8e91-4512f8605be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='fromAccountId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;fromAccountId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dc4df520-b3a1-4aa8-8bd2-01a9d699e7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fromAccountId</value>
      <webElementGuid>d4d665db-c54a-457a-b3c1-e4aa30f77992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56a3c90e-c138-4507-b2f8-ccad07de2288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                            16674
                        
                    </value>
      <webElementGuid>6fbe6336-7e05-498a-9451-02f7decefd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billpayForm&quot;)/form[1]/table[@class=&quot;form2&quot;]/tbody[1]/tr[13]/td[2]/select[@class=&quot;input&quot;]</value>
      <webElementGuid>4baefbc6-498e-4f40-b102-eff81ee9b2e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='fromAccountId']</value>
      <webElementGuid>cbc142a5-ff3d-479e-ba32-bf7a2db637db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billpayForm']/form/table/tbody/tr[13]/td[2]/select</value>
      <webElementGuid>53f368fd-c097-4e06-9aa6-9763424b98e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From account #:'])[1]/following::select[1]</value>
      <webElementGuid>c5dfe71e-dad2-4b8d-91c0-3a4e4b1b0e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount: $'])[1]/following::select[1]</value>
      <webElementGuid>ee0e4d4a-6298-465b-a9f9-6d8919be9b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill Payment Complete'])[1]/preceding::select[1]</value>
      <webElementGuid>eff62c21-58b3-4086-bbce-da078f620624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error!'])[1]/preceding::select[1]</value>
      <webElementGuid>d4cddbec-b2a7-4549-9457-d37f885962b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>367ecc9f-5321-49a5-8ec1-088ab80bfeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fromAccountId' and (text() = '
                        
                            16674
                        
                    ' or . = '
                        
                            16674
                        
                    ')]</value>
      <webElementGuid>decaa670-1d8b-46ea-a66d-e6e780a925a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
