<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ZipCode_TxBx</name>
   <tag></tag>
   <elementGuidId>e8faea43-043b-4dac-9270-ab49fd14d6f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='payee.address.zipCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;payee.address.zipCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;payee\.address\.zipCode&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82090e77-0061-49c6-a9aa-21946d6a6690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6f5ec2c-56c6-4e6f-b149-de7e0617ee03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.address.zipCode</value>
      <webElementGuid>4f9f9f2e-58f3-4dbd-8ab7-99f18a6ff5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billpayForm&quot;)/form[1]/table[@class=&quot;form2&quot;]/tbody[1]/tr[5]/td[2]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>25084cd5-446b-47be-8dd5-75af3a90ab53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='payee.address.zipCode']</value>
      <webElementGuid>c89b20fd-55bd-46e5-8b44-773361ffb57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billpayForm']/form/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>7574c151-3e10-4f18-8a43-d6fb75735cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>b9e74670-1bee-4afd-8e76-09381c18bd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payee.address.zipCode']</value>
      <webElementGuid>9bf85bed-0a24-4ff7-97c9-b1e6c6a154bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
